 /******************************************************************************
 *
 * Module: Ultrasonic Sensor
 *
 * File Name: ultrasonic.c
 *
 * Description: Header file for the Ultranoic sensor driver
 *
 * Author: Muhammad Salah
 *
 *******************************************************************************/


#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_

#include "../MCAL/common_macros.h"
#include "../MCAL/std_types.h"
#include "../MCAL/gpio.h"

/*******************************************************************************
 *                                Definitions                                  *
 *******************************************************************************/


#define ULTRASONIC_TRIGGER_PORT	PORTB_ID
#define ULTRASONIC_TRIGGER_PIN	PIN5_ID

#define ULTRASONIC_ECHO_PORT	PORTD_ID
#define ULTRASONIC_ECHO_PIN		PIN6_ID


/*******************************************************************************
 *                      Functions Definitions                                  *
 *******************************************************************************/


/*
 * Description:
 * 1- Initialize the ICU driver as required.
 * 2- Setup the ICU call back function.
 * 3- Setup the direction for the trigger pin as output pin through theGPIO driver.
 *
 */
void Ultrasonic_init();

/*
 * Description
 * 1- Send the trigger pulse by using Ultrasonic_Trigger function.
 * 2- Start the measurements by the ICU from this moment.
 */
uint16 Ultrasonic_readDistance(void);

/*
 * Description
 * 1- This is the call back function called by the ICU driver.
 * 2- This is used to calculate the high time (pulse time) generated by
 * the Ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void);



#endif /* ULTRASONIC_H_ */
